dotnet new sln
dotnet new xunit --name BeacomDwollaWeatherGrabberTest
dotnet new console --name BeacomDwollaWeatherGrabberCli
dotnet sln BeacomDwollaWeatherGrabber.sln add BeacomDwollaWeatherGrabberCli/BeacomDwollaWeatherGrabberCli.csproj 
dotnet sln BeacomDwollaWeatherGrabber.sln add BeacomDwollaWeatherGrabberTest/BeacomDwollaWeatherGrabberTest.csproj 
dotnet new classlib --name BeacomDwollaWeatherGrabberOpenWeatherService
dotnet new classlib --name BeacomDwollaWeatherGrabberInterfaces
dotnet sln BeacomDwollaWeatherGrabber.sln add BeacomDwollaWeatherGrabberInterfaces/BeacomDwollaWeatherGrabberInterfaces.csproj 
dotnet sln BeacomDwollaWeatherGrabber.sln add BeacomDwollaWeatherGrabberOpenWeatherService/BeacomDwollaWeatherGrabberOpenWeatherService.csproj 
dotnet add BeacomDwollaWeatherGrabberCli/BeacomDwollaWeatherGrabberCli.csproj reference BeacomDwollaWeatherGrabberInterfaces/BeacomDwollaWeatherGrabberInterfaces.csproj 
dotnet add BeacomDwollaWeatherGrabberCli/BeacomDwollaWeatherGrabberCli.csproj reference BeacomDwollaWeatherGrabberOpenWeatherService/BeacomDwollaWeatherGrabberOpenWeatherService.csproj 
dotnet add BeacomDwollaWeatherGrabberTest/BeacomDwollaWeatherGrabberTest.csproj reference BeacomDwollaWeatherGrabberInterfaces/BeacomDwollaWeatherGrabberInterfaces.csproj 
dotnet add BeacomDwollaWeatherGrabberOpenWeatherService/BeacomDwollaWeatherGrabberOpenWeatherService.csproj reference BeacomDwollaWeatherGrabberInterfaces/BeacomDwollaWeatherGrabberInterfaces.csproj
dotnet add BeacomDwollaWeatherGrabberTest/BeacomDwollaWeatherGrabberTest.csproj package Moq
dotnet add BeacomDwollaWeatherGrabberTest/BeacomDwollaWeatherGrabberTest.csproj reference BeacomDwollaWeatherGrabberOpenWeatherService/BeacomDwollaWeatherGrabberOpenWeatherService.csproj 
